### ISSUE TITLE
About the normal channel

### ISSUE THREAD

**Issue by warriorsniu** [cszyzhang/riconv2#4]
In your paper, you provided the result when not using the normal channel. However, it leads to an error when testing the data without normal. 
![image](https://user-images.githubusercontent.com/58773198/197702986-aedcc5fd-d7fa-45be-a543-3c5622b0a127.png)
It seems that LRA is not computed when normal is None.
![image](https://user-images.githubusercontent.com/58773198/197703446-b5708290-7e3b-445e-978a-776975455007.png)

**Comment by cszyzhang** [comment]
you can just replace 'norm=None' with 'norm=compute_LRA(xyz)'.

**Comment by warriorsniu** [comment]
I have tried the method and it did work! Thank you!
