### ISSUE TITLE
No module named 'pointnet2_cuda'

### ISSUE THREAD

**Issue by JianrongYan** [cszyzhang/riconv2#5]
Hi, thanks for your open source code firstly, but I met a problem that "No module named 'pointnet2_cuda'" even though I had run the setup.py without any errors. I 'll appreciate it if you can solve my problem.

**Comment by cszyzhang** [comment]
you can check if your nvcc version does match your pytorch cuda runtime lib version. For example, if your nvcc is 11, you need to install torch with cuda11 as well.

**Comment by JianrongYan** [comment]
> you can check if your nvcc version does match your pytorch cuda runtime lib version. For example, if your nvcc is 11, you need to install torch with cuda11 as well.

thanks!
