### ISSUE TITLE
Question on Experiments

### ISSUE THREAD

**Issue by JianrongYan** [cszyzhang/riconv2#6]
I am a student and recently I was learning about rotation invariance of point clouds. After reading your article,  I benefited a lot, but I have a few questions about the experiments.  Why doesn't any rotation transformations exist on dataset class, and what kind of rotation augmentation used on training for the pretrained models. Thanks a lot.

**Comment by cszyzhang** [comment]
Rotation transformations are usually added manually as a way for data augmentation. The type of rotation in 3D space is random rotation.

**Comment by JianrongYan** [comment]
> 

I got it! Thanks a lot.
